apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
spec:
  selector:
    app: "{{ .Values.appName }}-match" #should be same as deployment's spec.selector.matchLabels.app name
    deploymentconfig: "{{ .Values.appName }}-{{ .Values.color }}"
  ports:
    - name: http
      protocol: TCP
      port: 5081
      targetPort: 5081
  type: "{{ .Values.serviceType }}"