apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.appName }}-vs"
spec:
  hosts:
    - "*"
  gateways:
    - "bookmymovie-istio-gateway"
  http:
    - route:
        - destination:
            host: "{{ .Values.appName }}-service"
            port:
              number: 8081