# Declare variables to be passed into your templates.
appName: poc-spring-boot-genai
configDir: env/envfolder/app-config
color: green
imagePullPolicy: Never #For local environment
#imagePullPolicy: IfNotPresent #For higher environments
serviceType: ClusterIP