name: CI/CD Pipeline
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: List Current Directory
        run: ls -ltr
      - name: Docker Image Build
        run: docker build . --file Dockerfile --tag us-central1-docker.pkg.dev/sab-dev-storage-453204/sab-dev-repo/poc-spring-boot-genai-image
      - name: GCP Project Login
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GAR_SERVICE_ACCOUNT_KEY }}
      - name: Cloud SDK Setup
        uses: google-github-actions/setup-gcloud@v1
      - name: Docker Auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: GAR Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/sab-dev-storage-453204/sab-dev-repo/poc-spring-boot-genai-image
      - name: Helm Installation
        run: >-
          -| wget https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz tar -xvf 
          helm-v3.12.0-linux-amd64.tar.gz sudo mv linux-amd64  /usr/local/bin
          helm version