name: CI/CD Pipeline
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: List Current Directory
        run: ls -ltr
      - name: Docker Image Build
        run: docker build . --file Dockerfile --tag gcr.io/sab-dev-storage-453204/poc-spring-boot-genai-image
      - name: GCP Project Login
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: GCR Docker Authentication
        run: |-
          gcloud auth configure-docker --quiet
      - name: Docker Image Push in GCR
        run: |-
          docker tag poc-spring-boot-genai-image:latest gcr.io/${{ env.PROJECT_ID }}/poc-spring-boot-genai-image:latest 
          docker push gcr.io/${{ env.PROJECT_ID }}/poc-spring-boot-genai-image:latest