name: Helm Pipeline
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Date Print
        run: echo "$(date)"
      - name: Present Directory Print
        run: echo "$(pwd)"
      - name: Listing Directory Items
        run: ls -ltr
      - name: Change Directory
        run: cd ./configuration/helm
      - name: Listing Directory Items Now
        run: ls -ltr
      - name: Helm Installation Check
        run: helm version