name: Helm Pipeline
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Helm Availability Check
        run: echo helm version
      - name: Helm Installation
        run: -|
          wget https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz