name: Helm Pipeline
on:
  workflow_dispatch:
    branches:
      - master
env:
  APP_NAME: poc-spring-boot-genai-parent
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Present Directory Print
        run: echo "$(pwd)"
      - name: Listing Directory Items
        run: ls -ltr
      - name: Helm Directory
        run: echo /home/runner/work/$APP_NAME/$APP_NAME/configuration/helm
      - name: Helm Installation Check
        run: helm version
      - name: Helm Init
        run: helm lint /home/runner/work/$APP_NAME/$APP_NAME/configuration/helm
      #- name: Helm Application Installation
      #  run: helm install --set configDir=env/GCP-Dev/app-config poc-spring-boot-genai-parent-helm --namespace poc-spring-boot-genai-parent-namespace /home/runner/work/poc-spring-boot-genai-parent/poc-spring-boot-genai-parent/configuration/helm --dry-run