name: Helm Pipeline
on:
  workflow_dispatch:
    branches:
      - master
env:
  APP_NAME: poc-spring-boot-genai
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Present Directory Print
        run: echo "$(pwd)"
      - name: Listing Directory Items
        run: ls -ltr
      - name: Helm Directory
        run: echo /home/runner/work/$APP_NAME-parent/$APP_NAME-parent/configuration/helm
      - name: Helm Version Check
        run: helm version
      - name: Helm Init
        run: helm lint /home/runner/work/$APP_NAME-parent/$APP_NAME-parent/configuration/helm
      #- name: Helm Application Installation
      #  run: helm install --set configDir=env/GCP-Dev/app-config $APP_NAME-helm --namespace $APP_NAME-namespace /home/runner/work/$APP_NAME-parent/$APP_NAME-parent/configuration/helm --dry-run