name: Helm Pipeline
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Helm Availability Check
        run: helm version
      - name: Helm Plugins Check
        run: helm plugin list