name: Helm Pipeline
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Date Print
        run: echo "$(date)"
      - name: Helm Installation Check
        run: helm version